---
title: 'Suivi des Routes Haïtiennes avec l’utilisation de R et OpenStreetMap '
author: FXLT
date: '2019-05-31'
slug: suivi-des-routes-haïtiennes-avec-l-utilisation-de-r-et-openstreetmap
categories:
  - R
  - OSM
  - cartography
  - haiti
tags:
  - R
  - OSM
---
# chargement des paquetages nécessaires
```{r setup, include=TRUE, eval=FALSE}

library(osmdata)
library("sf")
library("units")
library("dplyr")
library("tidyverse")
library("tidyr")
library("stringr")
#library(cartography)
#library("DT")
library("formattable")
```

# routes nationales
```{r r_nat, include=TRUE, eval=FALSE}

#définition des bornes 
q0 <- opq(bbox = c(-75.04211,17.34015 , -71.59241, 20.42186))
#extraction des relations 
nat <- add_osm_feature(opq = q0, key = "network", value = "HT:RN-road")
#transformation requete en sf
res1 <- osmdata_sf(nat)
# prise en compte géométrie relations routes
route <- st_geometry(res1$osm_multilines)
#utiliser SCR utm 18n Haïti
route <- st_transform(route, 32618)
#calculer longueur chaque route
res1$osm_multilines$longueurOsm <- st_length(res1$osm_multilines)/1000
#sélection des colonnes à garder ref et longueur
osm <- res1$osm_multilines[,c(7,11)]
osm <- distinct(osm, ref, .keep_all = TRUE)


#charger shp routes ministere
mtptc <- read_sf("~/Documents/haiti_administratif/transport/reseau_routier_haiti/reseau_routier_haiti.shp",  quiet = TRUE, stringsAsFactors = FALSE)
# sélectionner uniquement routes départementales
mtptc <- mtptc[mtptc$COD1_TYP == "RN",]
# dissoudre en fonction ref de routes
mtptc <- mtptc %>% group_by(mtptc$CODE_MTPTC) %>% summarize()
#calcul longueur
mtptc$longueurM <- st_length(mtptc)/1000
# passage en data.frame pour permettre fusion 2 tableaux
mtptc <- as.data.frame(mtptc)
#on retire la colonne géométrie
mtptc <- mtptc[,-c(2)]
#calcul nombre caractères réf dans osm pour choisir comment les concaténer
osm$nbc <- str_length(osm$ref)
# concaténation des ref dans osm pour que cela corresponde à celles du ministère
osm$ref <- ifelse(osm$nbc == 4, paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -1)), sep  = ""),
                  paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -2,-1)), sep  = ""))
                  


#fusion tableau mtptc et osm par les références des routes
compar <- full_join(mtptc, osm, by = c("mtptc$CODE_MTPTC" = "ref"))
#activation des variables en entrée directe
attach(compar)
# arrondi longueur à 2 décimales 
compar$longueurM <- round(compar$longueurM, digits = 2)
compar$longueurOsm <- round(compar$longueurOsm, digits = 2)
#calcul de la différence entre distance Ministère et OSM
compar$diffL <- longueurM - longueurOsm
compar$diffL <- round(compar$diffL, digits = 2)
#ajout colonne pourcentage finition dans osm par rapport Ministère
compar$pourdiff <- longueurOsm *100/ longueurM
#arrondi à deux décimales
compar$pourdiff<-  round(compar$pourdiff, digits = 2)
#renommer colonne
#compar$ref <- colnames(compar$`mtptc$CODE_MTPTC`)  

#retire colonne géométrie et nbc
compar <- compar[,-c(4,5)]
#compar <- compar[-c(36,37),]
#changement des noms des colonnes
names(compar) <- c("Réf", "LongeurMinis en km", "LongueurOSM en km", "Différence en km", "Complétude en %")

#affichage du résultat dans un tableau
formattable(compar, list(
  "Différence en km" = color_tile("green", "red"),
  area(col = c("Complétude en %")) ~ proportion_bar("pink", 0.2)
))
```

# routes départementales
```{r r_dep, include=TRUE, eval=FALSE}
#définition des bornes 
q0 <- opq(bbox = c(-75.04211,17.34015 , -71.59241, 20.42186))
#extraction des relations 
dep <- add_osm_feature(opq = q0, key = "network", value = "HT:RD-road")
#transformation requete en sf
res1 <- osmdata_sf(dep)
# prise en compte géométrie relations routes
route <- st_geometry(res1$osm_multilines)
#utiliser SCR utm 18n Haïti
route <- st_transform(route, 32618)
#calculer longueur chaque route
res1$osm_multilines$longueurOsm <- st_length(res1$osm_multilines)/1000
#sélection des colonnes à garder ref et longueur
osm <- res1$osm_multilines[,c(7,12)]


#charger shp routes ministere
mtptc <- read_sf("~/Documents/haiti_administratif/transport/reseau_routier_haiti/reseau_routier_haiti.shp",  quiet = TRUE, stringsAsFactors = FALSE)
# sélectionner uniquement routes départementales
mtptc <- mtptc[mtptc$COD1_TYP == "RD",]
# dissoudre en fonction ref de routes
mtptc <- mtptc %>% group_by(mtptc$CODE_MTPTC) %>% summarize()
#calcul longueur
mtptc$longueurM <- st_length(mtptc)/1000
# passage en data.frame pour permettre fusion 2 tableaux
mtptc <- as.data.frame(mtptc)
#on retire la colonne géométrie
mtptc <- mtptc[,-c(2)]
#calcul nombre caractères réf dans osm pour choisir comment les concaténer
osm$nbc <- str_length(osm$ref)
# concaténation des ref dans osm pour que cela corresponde à celles du ministère
osm$ref <- ifelse(osm$nbc == 5, paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -2,-1)), sep  = ""),
          ifelse(osm$nbc == 6, paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -3,-1)), sep  = ""),
          paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -4,-1)), sep  = ""))
                   )

#fusion tableau mtptc et osm par les références des routes
compar <- full_join(mtptc, osm, by = c("mtptc$CODE_MTPTC" = "ref"))
#activation des variables en entrée directe
attach(compar)
# arrondi longueur à 2 décimales 
compar$longueurM <- round(compar$longueurM, digits = 2)
compar$longueurOsm <- round(compar$longueurOsm, digits = 2)
#calcul de la différence entre distance Ministère et OSM
compar$diffL <- longueurM - longueurOsm
compar$diffL <- round(compar$diffL, digits = 2)
#ajout colonne pourcentage finition dans osm par rapport Ministère
compar$pourdiff <- longueurOsm *100 / longueurM

#arrondi à deux décimales
compar$pourdiff<-  round(compar$pourdiff, digits = 2)
#renommer colonne
#compar$ref <- colnames(compar$`mtptc$CODE_MTPTC`)  

#retire colonne géométrie et nbc
compar <- compar[,-c(4,5)]
#compar <- compar[-c(36,37),]
#changement des noms des colonnes
names(compar) <- c("Réf", "LongeurMinis en km", "LongueurOSM en km", "Différence en km", "Complétude en %")

#affichage du résultat dans un tableau
formattable(compar, list(
  "Différence en km" = color_tile("green", "red"),
  area(col = c("Complétude en %")) ~ proportion_bar("pink", 0.2)
))
```



# routes communales
```{r r_com, include=TRUE, eval=FALSE}

#définition des bornes 
q0 <- opq(bbox = c(-75.04211,17.34015 , -71.59241, 20.42186))
#extraction des relations 
com <- add_osm_feature(opq = q0, key = "network", value = "HT:RC-road")
#transformation requete en sf
res1 <- osmdata_sf(com)
# prise en compte géométrie relations routes
route <- st_geometry(res1$osm_multilines)
#utiliser SCR utm 18n Haïti
route <- st_transform(route, 32618)
#calculer longueur chaque route
res1$osm_multilines$longueurOsm <- st_length(res1$osm_multilines)/1000
#sélection des colonnes à garder ref et longueur
osm <- res1$osm_multilines[,c(4,9)]
#permet d’enlever les doubles
#osm <- distinct(osm, ref, .keep_all = TRUE)


#charger shp routes ministere
comtp <- read_sf("~/Documents/haiti_administratif/transport/reseau_routier_haiti/reseau_routier_haiti.shp",  quiet = TRUE, stringsAsFactors = FALSE)
# sélectionner uniquement routes départementales
comtp <- comtp[comtp$COD1_TYP == "RC",]
# dissoudre en fonction ref de routes
comtp <- comtp %>% group_by(comtp$CODE_MTPTC) %>% summarize()
#calcul longueur
comtp$longueurM <- st_length(comtp)/1000
# passage en data.frame pour permettre fusion 2 tableaux
comtp <- as.data.frame(comtp)
#on retire la colonne géométrie
comtp <- comtp[,-c(2)]
#calcul nombre caractères réf dans osm pour choisir comment les concaténer
osm$nbc <- str_length(osm$ref)
# concaténation des ref dans osm pour que cela corresponde à celles du ministère
osm$ref <- ifelse(osm$nbc == 7, paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref,-4, -1)), sep  = ""),
                  paste(c(str_sub(osm$ref,1,2)),(str_sub(osm$ref, -2,-1)), sep  = ""))



#fusion tableau comtp et osm par les références des routes
commu <- full_join(comtp, osm, by = c("comtp$CODE_MTPTC" = "ref"))
#activation des variables en entrée directe
attach(commu)
# arrondi longueur à 2 décimales 
commu$longueurM <- round(commu$longueurM, digits = 2)
commu$longueurOsm <- round(commu$longueurOsm, digits = 2)
#calcul de la différence entre distance Ministère et OSM
commu$diffL <- longueurM - longueurOsm
commu$diffL <- round(commu$diffL, digits = 2)
#ajout colonne pourcentage finition dans osm par rapport Ministère
commu$pourdiff <- longueurOsm *100/ longueurM
#arrondi à deux décimales
commu$pourdiff<-  round(commu$pourdiff, digits = 2)
#renommer colonne
#commu$ref <- colnames(commu$`mtptc$CODE_MTPTC`)  

#retire colonne géométrie et nbc
commu <- commu[,-c(4,5)]
#commu <- commu[-c(36,37),]
#changement des noms des colonnes
names(commu) <- c("Réf", "LongeurMinis en km", "LongueurOSM en km", "Différence en km", "Complétude en %")
#15 premières références
com15 <- commu[1:23,]

#affichage du résultat dans un tableau
formattable(com15, list(
  "Différence en km" = color_tile("green", "red"),
  area(col = c("Complétude en %")) ~ proportion_bar("pink", 0.2)
))
#30 dernières références
com30 <- commu[24:47,]

png <- 
#affichage du résultat dans un tableau
formattable(com30, list(
  "Différence en km" = color_tile("green", "red"),
  area(col = c("Complétude en %")) ~ proportion_bar("pink", 0.2)
))
```